# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _flexmc
else:
    import _flexmc

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Token(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    Type_eof = _flexmc.Token_Type_eof
    Type_eol = _flexmc.Token_Type_eol
    Type_wsp = _flexmc.Token_Type_wsp
    Type_tab = _flexmc.Token_Type_tab
    Type_sym = _flexmc.Token_Type_sym
    Type_number = _flexmc.Token_Type_number
    Type_keyWord = _flexmc.Token_Type_keyWord
    Type_id = _flexmc.Token_Type_id
    Type_undefined = _flexmc.Token_Type_undefined

    def __init__(self, *args):
        _flexmc.Token_swiginit(self, _flexmc.new_Token(*args))

    def toString(self):
        return _flexmc.Token_toString(self)

    def type2String(self):
        return _flexmc.Token_type2String(self)
    type = property(_flexmc.Token_type_get)
    value = property(_flexmc.Token_value_get)
    __swig_destroy__ = _flexmc.delete_Token

# Register Token in _flexmc:
_flexmc.Token_swigregister(Token)


def __lshift__(output, token):
    return _flexmc.__lshift__(output, token)
class Lexer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, program):
        _flexmc.Lexer_swiginit(self, _flexmc.new_Lexer(program))

    def nextToken(self):
        return _flexmc.Lexer_nextToken(self)

    def reset(self):
        return _flexmc.Lexer_reset(self)
    __swig_destroy__ = _flexmc.delete_Lexer

# Register Lexer in _flexmc:
_flexmc.Lexer_swigregister(Lexer)



