name: CMake msvc build
on: [pull_request, workflow_dispatch]

jobs:

  windows-msvc-debug:

    # The below calls work around the issue:

    #  CMake Error at CMakeLists.txt:2 (project):
    #  The CMAKE_CXX_COMPILER:
    #
    #    cl.exe
    #
    #  is not a full path and was not found in the PATH.  Perhaps the extension is
    #  missing?

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: configure
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Vc\Auxiliary\Build\vcvarsall.bat" amd64 -vcvars_ver=14.3 || exit 1
          cmake --preset windows-msvc-debug

      - name: build
        shell: cmd
        working-directory: out/build/windows-msvc-debug
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Vc\Auxiliary\Build\vcvarsall.bat" amd64 -vcvars_ver=14.3 || exit 1
          cmake --build .

      - name: test
        working-directory: out/build/windows-msvc-debug/tests
        run: ctest -V
