name: Linux Benchmark Test
on: [pull_request, workflow_dispatch]

# Workaround for
#  CMake Error at CMakeLists.txt:2 (project):
#  The CMAKE_CXX_COMPILER:
#
#    cl.exe
#
#  is not a full path and was not found in the PATH.  Perhaps the extension is
#  missing?

jobs:

  windows-msvc:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: configure
        run: cmake --preset linux-gcc-release

      - name: build
        working-directory: out/build/linux-gcc-releasee
        run: cmake --build .

      - name: benchmark
        working-directory: out/build/linux-gcc-release/benchmarking/src
        run: benchmarking
